spring:
  output:
    ansi:
      enabled: always

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://host.docker.internal:8080/realms/saas-realm/protocol/openid-connect/certs

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

host.docker.internal:
  server-url: http://host.docker.internal:8080
  realm: saas-realm
  client-id: saas-client
  client-secret: eXuwLPfp0HT7sEfd4A9tl4epEIXhUMNb
  openIdConnectUrl: http://host.docker.internal:8080/realms/saas-realm/.well-known/openid-configuration
